export const HIDDEN_TAGS = [
	"special",
	"hackathon",
	"unfinished",
	"deprecated",
	"broken",
	"solutions",
]

export const SPECIAL_TAGS: [string, string, string][] = [
	["special", "⭐", "This is a special repository!"],
	["hackathon", "🧑‍💻", "This project was a hackathon project and most likely won't be updated"],
	["unfinished", "🚧", "This project has yet to be completed..."],
	["deprecated", "⚠️", "This project is not getting any further updates!"],
	["broken", "💥", "This project does not work!"],
]

export const TAG_CATEGORIES: [string, string[]][] = [
	[
		"Languages & Runtimes",
		[
			"rust",
			"typescript",
			"cpp",
			"java",
			"php",
			"javascript",
			"python",
			"nodejs",
			"bunjs",
			"dart",
			"solidity",
			"kotlin",
		],
	],
	[
		"Frameworks",
		[
			"laravel",
			"android",
			"angular",
			"arduino",
			"nextjs",
			"react",
			"chakraui",
			"materialui",
			"mantineui",
			"truffle",
			"discord",
			"express",
			"flask",
			"flutter",
			"jupyter",
			"reactnative",
			"redux",
			"tailwind",
			"tauri",
			"vue",
		],
	],
	[
		"Cloud Services",
		[
			"spotify",
			"firebase",
			"apigateway",
			"flyio",
			"dynamodb",
			"ec2",
			"postgresql",
			"mongodb",
			"rekognition",
			"s3",
			"vercel",
			"lambda",
			"sns",
			"youtube",
			"iotcore",
		],
	],
	[
		"DevOps Tools",
		[
			"phpunit",
			"jest",
			"cypress",
			"docker",
			"githubactions",
			"githubpages",
			"npm",
			"cargo",
			"notion",
		],
	],
]
